### ISSUE TITLE
Can't find in docs, how do I define a top level namespace?  Also optional function args?

### ISSUE THREAD

**Issue by ahungry** [Scriptor/pharen#65]
How do I define optional function arguments that include default values if not passed in?

Also, defining a top level namespace?

**Comment by Scriptor** [comment]
Top level namespaces are defined like the following:
```
(ns foo.bar)

(your-code-here)
```

Can you elaborate on what you mean by optional args? If you're looking for a way to do default argument values, it's like this:
```
(fn foo (arg1 [arg2 "default"])
  )

(foo "hello")
```
Notice the square brackets around the second argument. `arg1` is required, but if no arg2 is provided it defaults to "default".

**Comment by ahungry** [comment]
Thanks a ton @Scriptor - heavy user of PHP and Common Lisp, but it's been awhile since I did much/any clojure (not sure if that's what the default argument values are modeled after here or not).

**Comment by ahungry** [comment]
Oh, one more question when you get a chance - I see the file generated by pharen requires an absolute path pharen file (based on where pharen was when the install.sh script was run).  Does the pharen binary support including a copy of this file (full of pharen functions) in a relative path?

For instance, it would be nice if the function file could be autoloaded or just composer required (so I don't have an absolute path reference in the php file generated from the phn file)

**Comment by ahungry** [comment]
Also - does pharen have built in string access syntax at the moment?  Similar to using $string[0] or $string{0} to access the first character of a string stored in $string?

**Comment by Scriptor** [comment]
The default arguments is a custom syntax added for the sake of convenience. Clojure doesn't support default args, but since PHP does I figured it'd be nice to throw that in.

Unfortunately there's no way to use relative paths for files like lang.phn and the standard lib files. It simply wasn't something I considered when I first started working on this. Ideally it would be a simple Composer dependency. Hopefully I'll have time soon to fix the whole include path mess.

String access is done in the same what that array/list indexing is done:

```
(def s "foobar")
(:s 0) ; return 'f'
```
